version: '2.0'

services:
  database:
    container_name: pokemon_db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "dev"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "dev"
    ports:
      - "1433:1433"
