version: '2.0'

services:
  database:
    container_name: pokemon_sql_server
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "DevPass@w0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
