version: '2.0'

services:
  database:
    container_name: pokemon_psql
    image: postgres:13
    environment:
      POSTGRES_DB: pokemon_psql
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"
